import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HomeContextProvider from "./context/HomeContext";

const poppins = Poppins(
  {
    weight: ["100", "200", "500", "700", "800", "900"],
    subsets: ["latin"],
    variable: '--font-poppins'
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{
        backgroundImage: `url('/image/Wallpaper.jpg')`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundAttachment: 'fixed',
        height: '100vh', // Adiciona a altura de 100vh para ocupar toda a tela
      }}
      >
      <HomeContextProvider>
      <body className={poppins.variable}>{children}</body>
      </HomeContextProvider>
    </html>
  );
}
